// exports.About = require('./About')
// exports.Layout = require('./Layout')
// exports.Message = require('./Message')
// exports.MessageInputForm = require('./MessageInputForm')
// exports.SiteNav = require('./SiteNav')
// exports.VerticalChannelNavItem = require('./VerticalChannelNavItem')
export const VerticalChannelNav = require('./VerticalChannelNav').default
export const MessageList = require('./MessageList').default
export const MessageInputForm = require('./MessageInputForm').default
export const MessagePanel = require('./MessagePanel').default
